#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the countApplesAndOranges function below.
def countApplesAndOranges(s, t, a, b, apples, oranges):
    houselist=[int(s),int(t)]
    appleslist=[]
    orangelist=[]
    apple_count = 0
    orange_count = 0
    for items in apples:
        appleslist.append(int(items) + a)
    
    for items in oranges:
        orangelist.append(int(items)+b)
        
    for items in appleslist:
        if items >=s and items<=t:
            apple_count+=1
    for items in orangelist:
        if items >=s and items <=t:
            orange_count+=1
    
    print(apple_count)
    print(orange_count)
        

if __name__ == '__main__':
    st = input().split()

    s = int(st[0])

    t = int(st[1])

    ab = input().split()

    a = int(ab[0])

    b = int(ab[1])

    mn = input().split()

    m = int(mn[0])

    n = int(mn[1])

    apples = list(map(int, input().rstrip().split()))

    oranges = list(map(int, input().rstrip().split()))

    countApplesAndOranges(s, t, a, b, apples, oranges)

