#!/bin/python3

import os
import sys

#
# Complete the getTotalX function below.
#
def getTotalX(a, b):
    #
    # Write your code here.
    #
    last = a[len(a)-1]
    first = b[0]
    list1=[]
    list2=[]
    list3=[]
    while last <= first:
        list1.append(last)
        last+=1
    
    for items in list1:
        flag=0
        for integers in a:
            if items % integers != 0:
                flag = 1
                break
                
        if flag==0:
            list2.append(items)
            
    for items in list2:
        flag =0
        for integers in b:
            if integers%items !=0:
                flag = 1
                break
        
        if flag==0:
            list3.append(items)
    
    return len(list3)
            

if __name__ == '__main__':
    f = open(os.environ['OUTPUT_PATH'], 'w')

    nm = input().split()

    n = int(nm[0])

    m = int(nm[1])

    a = list(map(int, input().rstrip().split()))

    b = list(map(int, input().rstrip().split()))

    total = getTotalX(a, b)

    f.write(str(total) + '\n')

    f.close()

