#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the diagonalDifference function below.
def diagonalDifference(arr):
    rows = len(arr)
    left_sum = 0
    right_sum = 0
    left_index = 0 
    right_index = rows - 1 
    
    #compute one diagonal 
    while left_index < rows and right_index >= 0:
        left_sum += arr[left_index][left_index]
        right_sum += arr[left_index][right_index]
        left_index+=1
        right_index -= 1

    return abs(left_sum - right_sum)
    
    
    
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    result = diagonalDifference(arr)

    fptr.write(str(result) + '\n')

    fptr.close()

