#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the divisibleSumPairs function below.
def divisibleSumPairs(n, k, ar):
    
    count = 0
    ar.sort(key=int)
    for index in range(len(ar)-1):
        j = len(ar)-1
        while j>index and int(ar[j]) >= int(ar[index]):
            if((ar[j]+ar[index])%k == 0):
                count+=1
            j-=1
    
    return count

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nk = input().split()

    n = int(nk[0])

    k = int(nk[1])

    ar = list(map(int, input().rstrip().split()))

    result = divisibleSumPairs(n, k, ar)

    fptr.write(str(result) + '\n')

    fptr.close()

