#!/bin/python3

import os
import sys

#
# Complete the gradingStudents function below.
#
def gradingStudents(grades):
    #
    # Write your code here.
    #
    for index in range(0,len(grades)):
        if grades[index]%5==0:
            continue
        elif grades[index]<38:
            continue
        else:
            next_multiple = ((grades[index]//5) + 1)*5
            if next_multiple - grades[index] < 3:
                grades[index] = next_multiple
    return grades

if __name__ == '__main__':
    f = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    grades = []

    for _ in range(n):
        grades_item = int(input())
        grades.append(grades_item)

    result = gradingStudents(grades)

    f.write('\n'.join(map(str, result)))
    f.write('\n')

    f.close()

