#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the miniMaxSum function below.
def miniMaxSum(arr):
    myList = []
    sum = 0
    for items in arr:
        sum+=items
    for items in arr:
        a = sum - items
        myList.append(a)
    print(min(myList), max(myList))
    
    

if __name__ == '__main__':
    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)

