#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the plusMinus function below.
def plusMinus(arr):
    length = len(arr)
    positive = 0
    negative = 0 
    zeroes = 0
    
    for item in arr:
        if item > 0:
            positive+=1
        elif item < 0:
            negative+=1
        elif item == 0:
            zeroes+=1

    print(round((positive/length),6))
    print(round((negative/length),6))
    print(round((zeroes/length),6))
            
    

if __name__ == '__main__':
    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)

