#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the squares function below.
def squares(a, b):
    myList=[]
    count=0
    var1= math.sqrt(a)
    var2= math.sqrt(b)
    print(var1,var2)
    var1=math.ceil(var1) - 1 
    var2=math.floor(var2)
    print(var1,var2)
    return var2-var1
   
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input())

    for q_itr in range(q):
        ab = input().split()

        a = int(ab[0])

        b = int(ab[1])

        result = squares(a, b)

        fptr.write(str(result) + '\n')

    fptr.close()

