#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the sockMerchant function below.
def sockMerchant(n, ar):
    myList=[0]*101
    
    for elements in ar:
        myList[int(elements)]+=1
    
    sum = 0
    print(myList)
    for elements in myList:
        if elements>0:
            temp = (elements - elements % 2)//2
            print(temp)
            sum+=temp
    
    return sum

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    ar = list(map(int, input().rstrip().split()))

    result = sockMerchant(n, ar)

    fptr.write(str(result) + '\n')

    fptr.close()

